### ISSUE TITLE
r8168-lts not getting installed along linux-lts

### ISSUE THREAD

**Issue by Diyou** [endeavouros-team/EndeavourOS-ISO#44]
When selecting r8168 as the preferred driver at the end of the installation EOS will boot without internet connectivity if linux-lts kernels were selected to be installed previously.

**Comment by killajoe** [comment]
thanks for report.. seems we need to check this.  using https://aur.archlinux.org/packages/r8168-dkms could be the easiest way to solve this. if not we need to add script to get the info on lts kernel is added.. and install lts version in addition too..

**Comment by Diyou** [comment]
> using https://aur.archlinux.org/packages/r8168-dkms could be the easiest way to solve this.

If I'm not mistaken that would require linux-lts-headers which is a separate install option.

**Comment by killajoe** [comment]
> If I'm not mistaken that would require linux-lts-headers which is a separate install option.

yes you can create unworking installs when selecting and deselecting packages manually ;) 
```
- name: "LTS Kernel in addition"
  description: "Adding Long Term Supported Kernel in addition to main one"
  hidden: false
  selected: false
  expanded: false
  critical: true
  packages:
    - linux-lts
    - linux-lts-headers
```
The issue is that we need to develop hardware detection and package install solutions that we can use fur such resolutions, calamares does not do this. If we would go to inplmenet workarounds for every issue like this we would create a mess of code. So we will go to work aón a real solution, what means as long as we do not have this we will  more likely go to remove the LTS kernel option as long as we do not have a real solution to the underlaying problem.
